### ISSUE TITLE
update to match the webinar

### ISSUE THREAD

**Issue by pureptp** [fiskaltrust/middleware-demo-postman#1]
Hello,

you used a different set of requests for the webinar and I think somebody said that it will be made available.
will it be updated here?
was it published elsewhere?

Best regards,
Peter

**Comment by TSchmiedlechner** [comment]
Hello Peter, 
thanks for reaching out, and sorry for the late response. We just updated the Postman collection in #2, please re-import it via the link on the start page of the repository to get the latest version.

Does this include everything you need?

Best,
Tom

**Comment by pureptp** [comment]
Thanks!
Sorry for the late response too
